dist: "bionic"
language: "python"
python:
  - "3.7"
install:
  - pip install pip --upgrade
  - pip install tensorflow==2.1
  - pip install -r requirements.txt
#  - poetry install
script:
  - poetry run safety check
  - poetry run black . --check
#  - poetry run mypy app
  - poetry run pytest
