dist: "bionic"
language: "python"
python:
  - "3.7"
install:
  - pip install -r requirements.txt
script:
  - safety check
  - black . --check
  - pytest
  - coverage run -m pytest tests
after_success: coveralls
